name: myenv
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.07.03
  - cartopy
  - cmocean
  - gcsfs
  - hvplot
  - intake-xarray
  - matplotlib
  - numpy
  - pandas
  - xarray
  - xgcm
  - zfp
  - zfpy
  - pip
  - pip:
      - fpzip
      - sat-search
